# Generated by Django 4.1 on 2022-08-26 09:21
from datetime import datetime, timedelta
from math import ceil
import string

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_initial_parking_spaces(apps, schema_editor):
        ParkingSpace = apps.get_model('session', 'ParkingSpace')
        for i in range(30):
            letter = list(string.ascii_uppercase)[(i+1) % 10]
            floor = ceil((i+1) / 10)
            ParkingSpace.objects.create(
                code=f'{floor}{letter}',
                floor=floor
            )

    def create_initial_sessions(apps, schema_editor):
        Vehicle = apps.get_model('accounts', 'Vehicle')
        ParkingSpace = apps.get_model('session', 'ParkingSpace')
        Session = apps.get_model('session', 'Session')
        vehicles = Vehicle.objects.all()
        for vehicle in vehicles:
            Session.objects.create(
                vehicle=vehicle,
                parking_space=ParkingSpace.objects.get(id=vehicle.id*2),
                start=datetime.now() - timedelta(hours=6),
                end=datetime.now() + timedelta(hours=6),
                is_active=True,
            )

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('reservation', 'Reservation'), ('on_arrival', 'On Arrival')], default='on_arrival', max_length=15, verbose_name='session type')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='check in')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='check out')),
                ('is_active', models.BooleanField(default=False)),
                ('parking_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.parkingspace')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
        ),
        migrations.RunPython(create_initial_parking_spaces),
        migrations.RunPython(create_initial_sessions)
    ]
