# Generated by Django 4.1 on 2022-08-25 16:46

from math import ceil
import string

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def create_initial_parking_lots(apps, schema_editor):
        ParkingLot = apps.get_model('session', 'ParkingLot')
        for i in range(30):
            letter = list(string.ascii_uppercase)[(i+1)%10]
            floor = ceil((i+1) / 10)
            ParkingLot.objects.create(
                code=f'{floor}{letter}',
                floor=floor
            )

    initial = True

    dependencies = [
        ('accounts', '0002_vehicle'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('reservation', 'Reservation'), (
                    'on_arrival', 'On Arrival')], max_length=15, verbose_name='session type')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('check_in', models.DateTimeField(verbose_name='check in')),
                ('check_out', models.DateTimeField(verbose_name='check out')),
                ('is_active', models.BooleanField(default=False)),
                ('parking_lot', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.parkinglot')),
                ('payment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('vehicle', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicle')),
            ],
        ),

        migrations.RunPython(create_initial_parking_lots),
    ]
